version: "3.4"
services:
  mariadb:
    image: mariadb:10

    container_name: poslive-mariadb
    
    ports:
      - 3306:3306

    restart: on-failure

    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: poslive
      MYSQL_USER: henio
      MYSQL_PASSWORD: 123

    volumes:
      - poslive:/var/lib/mysql

volumes:
  poslive:
